// Copyright 2020 Trenina Elizaveta
#ifndef MODULES_TASK_1_TRENINA_E_CONVEX_HULL_GRAHAM_H_
#define MODULES_TASK_1_TRENINA_E_CONVEX_HULL_GRAHAM_H_


#endif  // MODULES_TASK_1_TRENINA_E_CONVEX_HULL_GRAHAM_H_
